version: "3.8"

volumes:
  rabbitmq_data:

services:

  ###################################
  # Order of start: 
  # Database
  # User
  # Image: 
  # Listing:
  # Rental:
  # SMS
  # Email
  # RabbitMQ 
  # Activity 
  # Error 
  # create-listing 
  # make-rental-request 
  # accept-rental-request 
  ###################################


  #######################################################
  # User: The User microservice
  #######################################################
  # order:
  #   build:
  #     context: ./user/
  #     dockerfile: user.Dockerfile
  #   image: <glendyslau>/user:esdproject
  #   restart: always
  #   environment:
  #     dbURL: mysql+mysqlconnector://is213@host.docker.internal:3306/order
  #     PYTHONUNBUFFERED: 1

  #######################################################
  # Image: The Image microservice
  #######################################################
  image:
    build:
      context: ./imageManagement/
      dockerfile: image.Dockerfile
    image: glendyslau/image:esdproject
    restart: always
    environment:
      PYTHONUNBUFFERED: 1

  #######################################################
  # Listing: The Listing microservice
  #######################################################
  listing:
    build:
      context: ./listing/
      dockerfile: listing.Dockerfile
    image: glendyslau/listing:esdproject
    restart: always
    environment:
      dbURL: mysql+mysqlconnector://is213@host.docker.internal:3306/user_listing
      PYTHONUNBUFFERED: 1

  #######################################################
  # Rental: The Rental microservice
  #######################################################
  rental:
    build:
      context: ./rental/
      dockerfile: rental.Dockerfile
    image: glendyslau/rental:esdproject
    restart: always
    environment:
      dbURL: mysql+mysqlconnector://is213@host.docker.internal:3306/user_listing
      PYTHONUNBUFFERED: 1

  #######################################################
  # Email: The Email microservice
  #######################################################
  email:
    build:
      context: ./emailnotification/
      dockerfile: email.Dockerfile
    image: glendyslau/emailnotification:esdproject
    restart: always
    environment:
      PYTHONUNBUFFERED: 1

  #######################################################
  # SMS: The SMS microservice
  #######################################################
  sms:
    build:
      context: ./smsnotification/
      dockerfile: sms.Dockerfile
    image: glendyslau/smsnotification:esdproject
    restart: always
    environment:
      PYTHONUNBUFFERED: 1

  ####################################
  # RabbitMQ: The messaging broker   
  ####################################
  rabbitmq:
    image: rabbitmq:3-management
    hostname: esdproject-rabbit
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq

  #################################################
  # Activity Log: The Activity Log microservice
  #################################################
  activity_log:
    build:
      context: ./logging/
      dockerfile: activity_log.Dockerfile
    image: glendyslau/activity_log:esdproject
    restart: always
    depends_on:
      - rabbitmq
    environment:
      rabbit_host: rabbitmq
      rabbit_port: 5672
      PYTHONUNBUFFERED: 1

  ###################################
  # Error: The Error microservice
  ###################################
  error:
    build:
      context: ./logging/
      dockerfile: error.Dockerfile
    image: glendyslau/error:esdproject
    restart: always
    depends_on:
      - rabbitmq
    environment:
      rabbit_host: rabbitmq
      rabbit_port: 5672
      PYTHONUNBUFFERED: 1

  ###############################################
  # create-listing 
  # make-rental-request 
  # accept-rental-request 
  ###############################################
  create_listing:
    build:
      context: ./complex/
      dockerfile: create_listing.Dockerfile
    image: glendyslau/create_listing:esdproject
    restart: always
    depends_on:
      - email
      - sms
      - image
      - listing
      - activity_log
      - error
      - rabbitmq
    environment:
      rabbit_host: rabbitmq
      rabbit_port: 5672
      listing_URL: http://listing:5304/listing
      user_URL: http://user:5303/userphone
      email_URL : http://email:5301/listedEmail
      sms_URL : http://sms:5306/listedSMS
      PYTHONUNBUFFERED: 1
    ports:
      - "5309:5309"

  ###############################################
  # create-listing 
  # make-rental-request 
  # accept-rental-request 
  ###############################################
  place_rental:
    build:
      context: ./complex/
      dockerfile: place_rental.Dockerfile
    image: glendyslau/place_rental:esdproject
    restart: always
    depends_on:
      - rental
      - email
      - listing
      - activity_log
      - error
      - rabbitmq
    environment:
      rabbit_host: rabbitmq
      rabbit_port: 5672
      listing_URL: http://listing:5304/listing
      email_URL : http://email:5301/requestedEmail
      sms_URL : http://sms:5306/requestedSMS
      rental_URL : http://rental:5305/rental
      PYTHONUNBUFFERED: 1
    ports:
      - "5307:5307"

  ###############################################
  # create-listing 
  # make-rental-request 
  # accept-rental-request 
  ###############################################
  accept_rental:
    build:
      context: ./complex/
      dockerfile: accept_rental.Dockerfile
    image: glendyslau/accept_rental:esdproject
    restart: always
    depends_on:
      - listing
      - rental
    environment:
      # rabbit_host: rabbitmq
      # rabbit_port: 5672
      listing_URL: http://listing:5304/listing
      rental_URL : http://rental:5305/rental
      PYTHONUNBUFFERED: 1

  ##################################
  # Book: The Book microservice
  ##################################
  # book:
  #   build:
  #     context: ./
  #     dockerfile: book.Dockerfile
  #   image: <glendyslau>/book:esdproject
  #   restart: always
  #   environment:
  #     dbURL: mysql+mysqlconnector://is213@host.docker.internal:3306/book
  #     PYTHONUNBUFFERED: 1
  #   ports:
  #     - "5000:5000"
